=== vishnuteja407/XML-and-Yang/FlightReservation/Reservation_format2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.airlines.com/Reservation" 
	xmlns:tns="http://www.airlines.com/Reservation" elementFormDefault="qualified">
	
	<element name="reservation"> 
	
	<complexType>
		<sequence>
			<element name="flight" type="tns:flight"/>
			<element name="passenger" type="tns:passenger"/>
		</sequence>
	</complexType>
	
	</element>
	
	<complexType name="passenger">
		<sequence>
			<element name="lastName" type="string"/>
			<element name="firstName" type="string"/>
			<element name="middleName" type="string"/>
			<element name="email" type="string"/>
			<element name="phone" type="string"/>
		</sequence>
	</complexType>
	
	<complexType name="flight">
		<sequence>
			<element name="flightNumber" type="string"/>
			<element name="operatingAirlines" type="string"/>
			<element name="arrivalCity" type="string"/>
			<element name="dateOfDepature" type="date"/>
			<element name="estimatedDepatureTime" type="time"/>
		</sequence>
	</complexType>
	
	
	
	
</schema>

=== vishnuteja407/XML-and-Yang/FlightReservation/Reservation2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:reservation xmlns:tns="http://www.airlines.com/Reservation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.airlines.com/Reservation Reservation_format2.xsd ">
  <tns:flight>
    <tns:flightNumber>tns:flightNumber</tns:flightNumber>
    <tns:operatingAirlines>tns:operatingAirlines</tns:operatingAirlines>
    <tns:arrivalCity>tns:arrivalCity</tns:arrivalCity>
    <tns:dateOfDepature>2001-01-01</tns:dateOfDepature>
    <tns:estimatedDepatureTime>12:00:00</tns:estimatedDepatureTime>
  </tns:flight>
  <tns:passenger>
    <tns:lastName>tns:lastName</tns:lastName>
    <tns:firstName>tns:firstName</tns:firstName>
    <tns:middleName>tns:middleName</tns:middleName>
    <tns:email>tns:email</tns:email>
    <tns:phone>tns:phone</tns:phone>
  </tns:passenger>
</tns:reservation>
