=== vishnuteja407/XML-and-Yang/PatientSchema/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vishnuteja407.com/Patient" xmlns:tns="http://www.vishnuteja407.com/Patient" xmlns:common="http://www.vishnuteja407.com/Common" elementFormDefault="qualified">
	
	<include schemaLocation="PaymentType.xsd"/>  <!--  works if elements are from same namespace -->
	
	<import schemaLocation="Common.xsd" namespace="http://www.vishnuteja407.com/Common"/>
	
	
	<element name="Patient" type="tns:Patient"/>
	
	<complexType name="Patient">
		<sequence>
			<element name="name" type="tns:String15Chars"/>
			<element name="age" type="int"/>
			<element name="email" type="string" minOccurs="0"/>
			<element name="gender" type="tns:Gender"/>
			<element name="phone" type="string" maxOccurs="unbounded"/>
			<element name="paymentType" type="tns:PaymentType"/>
		</sequence>
		
		<attribute name="id" type="common:id" use="required"/>
		
	</complexType>
	
	
	<simpleType name="String15Chars">
		<restriction base="string">
			<maxLength value="15"/>
		</restriction>
	</simpleType>
	
	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M"/>
			<enumeration value="F"/>
		</restriction>
	</simpleType>
	
</schema>

=== vishnuteja407/XML-and-Yang/PatientSchema/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Patient xmlns:tns="http://www.vishnuteja407.com/Patient" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vishnuteja407.com/Patient Patient.xsd " id="1">
  <tns:name>Vishnu</tns:name>
  <tns:age>29</tns:age>
  <tns:email>vishnuteja407@gmail.com</tns:email>
  <tns:gender>M</tns:gender>
  <tns:phone>1234567809</tns:phone>
  <tns:paymentType>
    <tns:cash>8000</tns:cash>
  </tns:paymentType>
</tns:Patient>
